# Generated by Django 4.0.2 on 2022-03-30 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy_app', '0008_alter_application_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('N', 'Не ищу работу'), ('M', 'Рассматриваю предложения'), ('Y', 'Ищу работу')], default='M', max_length=1)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(choices=[('IN', 'Стажер'), ('JU', 'Джуниор'), ('MI', 'Миддл'), ('SE', 'Синьор'), ('LE', 'Лид')], default='IN', max_length=2)),
                ('education', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('portfolio', models.TextField()),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacancy_app.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
