# Generated by Django 4.0.2 on 2022-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(),
        ),
    ]
