# Generated by Django 4.0.2 on 2022-03-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_app', '0006_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vacancy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancy_app.vacancy'),
        ),
    ]
